version: '3'

services:
  barber_postgres:
    image: postgres:latest
    container_name: barber_postgres-fsw
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: